Votedress.WebApp/Controllers/GardropController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Votedress.BusinessLayer;
using Votedress.Entities.SadeModeller;
using Votedress.Entities.VeritabaniModellerim;
using Votedress.Entities.ViewModellerim;
using Votedress.WebApp.App_Start;

namespace Votedress.WebApp.Controllers
{
    public class GardropController : Controller
    {
        // GET: Gardrop
        [LoginFilter]
        [BireyselUserFilter]
        [LoglamaFilter]
        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult Index()
        {
            VotedressUser user = new VotedressUser();
            user = Session["login"] as VotedressUser;
            ViewBag.SessionID = user.id.ToString();

            return View();
        }


        [HttpGet]
        [LoginFilter]
        [BireyselUserFilter]
        public JsonResult MagazalariGetir(int page, int CityID, int CountyID, int NeighborhoodID, int FranchiseID)
        {
            int pageSize = 12;
            VotedressUserManager userManager = new VotedressUserManager();
            List<VotedressUser> filtreliMagazalar = userManager.pagerMagazalariGetir(CityID, CountyID, NeighborhoodID, FranchiseID, page, pageSize);

            List<Magazalar_sade> sade_magazalar = filtreliMagazalar.Select(x => new Magazalar_sade
            {

                MagazaGuid = x.id,
                MagazadakilerSayisi = x.OnlineCount,
                SirketAdi = x.UserDetail.CompanyName,
                SirketResmi = x.ProfileImage,
                FranchiseAdi = x.Franchise.FranchiseName,
                FranchiseLogo = x.Franchise.FranchiseLogo,
                TelNo = x.UserDetail.PhoneNumber,
                Adres = x.UserDetail.AdressDetail,
                Sehir = x.UserDetail.City.CityName,
                Ilce = x.UserDetail.County.CountyName,
                Mahalle = x.UserDetail.Neighborhood.NeighborhoodName

            }).ToList();


            return Json(sade_magazalar, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        [OutputCache(Duration = 999999999)]
        public JsonResult FranchiseleriGetir()
        {
            FranchiseManager franchiseManager = new FranchiseManager();
            List<Franchise> franchise = franchiseManager.FranchiseleriGetir();

            return Json(franchise, JsonRequestBehavior.AllowGet);
        }

        [LoginFilter]
        [BireyselUserFilter]
        [LoglamaFilter]
        [OutputCache(Duration = 0)]
        public ActionResult Magaza(Guid id)
        {
            VotedressUser user = new VotedressUser();
            user = Session["login"] as VotedressUser;

            ProductManager productManager = new ProductManager();
            List<Product> urunler = productManager.UrunleriGetir(id);


            CollectionManager collectionManager = new CollectionManager();

            List<Category> kategoriler = collectionManager.KategorileriGetir(id);

            var JsonModel = new
            {

                urunler = urunler.Select(x => new
                {

                    id = x.id,
                    productName = x.ProductName,
                    productImage = x.ProductImage,
                    Collections = x.ProductCategory.Select(k => new
                    {
                        id = k.Category.id,
                        collectionName = k.Category.CategoryName,
                        description = k.Category.Description,
                        createDate = k.Category.CreateDate,
                    }),
                    price = x.Price,
                    shortDescription = x.ShortDescription,
                    longDescription = x.LongDescription,
                    uploadDate = x.UploadDate,
                    detail = x.ProductSize.Select(k => new
                    {
                        productSize = k.Size,
                        productColors = k.ProductColor.Select(y => new
                        {
                            stockCount = y.StockCount,
                            color = y.ProductColorDetail.Select(u => new
                            {
                                colorName = u.Color.ColorName,
                                colorCode = u.Color.ColorCode,

                            }),
                            productImageGallery = y.ProdutImageGallery.Select(u => new
                            {
                                id = u.id,
                                imagePath = u.ImagePath
                            })
                        }),
                    }),

                }),

                magazaAdi = urunler[0].User.UserDetail.CompanyName,
                magazaId = urunler[0].User.id,
                kategoriler = kategoriler.Select(k => new
                {
                    id = k.id,
                    collectionName = k.CategoryName,
                    description = k.Description,
                    createDate = k.CreateDate,
                }),


            };

            return View(JsonModel);
        }


        [LoginFilter]
        [BireyselUserFilter]
        public JsonResult UrunFiltrele(int page, Guid magazaId, List<int> renkId, List<Guid> kategoriId, int? enDusukFiyat, int? enYuksekFiyat)
        {
            VotedressUser user = new VotedressUser();
            user = Session["login"] as VotedressUser;

            if (enDusukFiyat == null)
            {
                enDusukFiyat = 0;
            }

            if (enYuksekFiyat == null)
            {
                enYuksekFiyat = 0;
            }

            ProductManager productManager = new ProductManager();
            List<Product> urunler = productManager.SayfalamaliUrunleriGetir(page, 12, magazaId, renkId, kategoriId, enDusukFiyat.Value, enYuksekFiyat.Value);


            CollectionManager collectionManager = new CollectionManager();

            List<Category> kategoriler = collectionManager.KategorileriGetir(magazaId);

            if (urunler.Count != 0)
            {


                var JsonModel = new
                {
                    urunler = urunler.Select(x => new
                    {
                        id = x.id,
                        productName = x.ProductName,
                        productImage = x.ProductImage,
                        Collections = x.ProductCategory.Select(k => new
                        {
                            id = k.Category.id,
                            collectionName = k.Category.CategoryName,
                            description = k.Category.Description,
                            createDate = k.Category.CreateDate,
                        }),
                        price = x.Price,
                        shortDescription = x.ShortDescription,
                        longDescription = x.LongDescription,
                        uploadDate = x.UploadDate,
                        detail = x.ProductSize.Select(k => new
                        {
                            productSize = k.Size,
                            productColors = k.ProductColor.Select(y => new
                            {
                                stockCount = y.StockCount,
                                color = y.ProductColorDetail.Select(u => new
                                {
                                    colorName = u.Color.ColorName,
                                    colorCode = u.Color.ColorCode,
                                }),
                                productImageGallery = y.ProdutImageGallery.Select(u => new
                                {
                                    id = u.id,
                                    imagePath = u.ImagePath
                                })
                            }),
                        }),

                    }),

                    magazaAdi = urunler[0].User.UserDetail.CompanyName,
                    kategoriler = kategoriler.Select(k => new
                    {
                        id = k.id,
                        collectionName = k.CategoryName,
                        description = k.Description,
                        createDate = k.CreateDate,
                    }),

                };

                return Json(JsonModel, JsonRequestBehavior.AllowGet);
            }
            return Json(null, JsonRequestBehavior.AllowGet);

        }

        [LoginFilter]
        [BireyselUserFilter]
        public JsonResult UrunDetayiGetir(Guid UrunID)
        {
            ProductManager productManager = new ProductManager();
            Product urun = productManager.UrunGetir(UrunID);

            int commentCount = urun.ProductComment.Count;
            for (int i = 0; i < urun.ProductComment.Count; i++)
            {
                commentCount = commentCount + urun.ProductComment[i].ProductCommentReply.Count();
            }


            SocialShareManager socialShareManager = new SocialShareManager();
            List<SocialShare> urunPaylasimi = socialShareManager.UrunPaylasimlariniGetir(UrunID);

            OylamaManager oylamaMnager = new OylamaManager();
            int urunluOylamalarCount = oylamaMnager.UrunluOylamalariGetir(UrunID).Count();


            int facebookShareCount = urunPaylasimi.Where(x => x.SocialName == "facebook").Count();
            int instagramShareCount = urunPaylasimi.Where(x => x.SocialName == "instagram").Count();
            int twitterShareCount = urunPaylasimi.Where(x => x.SocialName == "twitter").Count();
            int votedressShareCount = urunPaylasimi.Where(x => x.SocialName == "votedress").Count();


            var JsonModel = new
            {
                urun = new
                {
                    id = urun.id,
                    productName = urun.ProductName,
                    productImage = urun.ProductImage,
                    Collections = urun.ProductCollection.Select(k => new
                    {

Votedress.WebApp/Controllers/NavbarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Votedress.BusinessLayer;
using Votedress.Entities.SadeModeller;
using Votedress.Entities.VeritabaniModellerim;
using Votedress.Entities.ViewModellerim;
using Votedress.WebApp.App_Start;

namespace Votedress.WebApp.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        [LoginFilter]
        public ActionResult KısaYollar()
        {
            VotedressUser kullanici = Session["login"] as VotedressUser;

            KısaYollarViewModel view_model = new KısaYollarViewModel();
            PrivateMessageManager privatemessage_manager = new PrivateMessageManager();
            view_model.GorulmemisMesajlar = privatemessage_manager.GorulmemisMesajlariGetir(kullanici.id).Select(x => new PrivateMessage_sade() {

                userId=x.User.id,
                adSoyad = x.User.UserDetail.Name + " " + x.User.UserDetail.SurName,
                GonderilmeTarihi = x.GöndermeTarihi.ToString(),
                Message=x.Message,
                ProfilImage=x.User.ProfileImage,
                Sahip = (x.User.id == kullanici.id) ? true : false

            }).ToList();


            BahsedilenManager bahsedilenManager = new BahsedilenManager();
            List<Bahsedilen_sade> bahsedenler = bahsedilenManager.BahsedenleriGetir(kullanici.id);
            view_model.Bahsedenler = bahsedenler;


            FriendManager friendManager = new FriendManager();
            List<Friend> arkadaslikIstekleri = friendManager.ArkadaslikIsteklerimiGetir(kullanici.id);
            view_model.ArkadaslikIsteklerim = arkadaslikIstekleri.Select(x => new Friend_sade()
            {
                UserId=x.User.id,
                UserNameSurname=x.User.UserDetail.Name+" "+ x.User.UserDetail.SurName,
                UserProfileImage=x.User.ProfileImage,
                Tarih=x.ArkadaslikTarihi,

            }).ToList();

            CartManager cartManager = new CartManager();

            Cart carts = cartManager.SepetimiGetir(kullanici.id);
            if(carts!=null)
            {
                List<Cart_sade> cart_Sades = carts.CartDetail.Select(x => new Cart_sade()
                {

                    id = x.id,
                    Count = x.ProductCount,
                    ProductId = x.Product.id,
                    ProductName = x.Product.ProductName,
                    ProductImage = x.Product.ProductImage,
                    ProductPrice = x.Product.Price,
                    ProductColorId = x.ProductColorId,
                    Size = x.Size


                }).ToList();
                view_model.Cart_Sades = cart_Sades;
            }
         

            return View(view_model);
        }
    }
}

Votedress.WebApp/Controllers/OylamaController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Votedress.BusinessLayer;
using Votedress.Entities.SadeModeller;
using Votedress.Entities.VeritabaniModellerim;
using Votedress.WebApp.App_Start;

namespace Votedress.WebApp.Controllers
{
    public class OylamaController : Controller
    {
        // GET: Oylama
        [LoginFilter]
        [BireyselUserFilter]
        [LoglamaFilter]
        public ActionResult Index()
        {
            VotedressUser user = new VotedressUser();
            user = Session["login"] as VotedressUser;

            OylamaManager vote_manager = new OylamaManager();
            Vote_sade oylama = vote_manager.OylamaGetirOylamakIcin(user.id);

            if (oylama != null)
            {
                InVoteChatManager invoteChatManager = new InVoteChatManager();
                if (invoteChatManager.Chattemiyim(user.id, oylama.id) == null)
                {
                    VotedressUserDetailManager userdetail_Manager = new VotedressUserDetailManager();
                    UserDetail kullanici_detayi = new UserDetail();
                    kullanici_detayi = userdetail_Manager.GetUserDetail(user.id);
                    VotedressUser_sade sade_kullanici = new VotedressUser_sade()
                    {
                        id = kullanici_detayi.UserId,
                        SocialId = kullanici_detayi.User.SocialId,
                        SocialName = kullanici_detayi.User.SocialName,
                        Name = kullanici_detayi.Name,
                        SurName = kullanici_detayi.SurName,
                        Birthday = kullanici_detayi.Birthday,
                        Email = kullanici_detayi.User.Email,
                        ProfileImage = kullanici_detayi.User.ProfileImage,
                        Sex = kullanici_detayi.Sex,

                    };
                    InVoteChatManager repo_invotechatManager = new InVoteChatManager();
                    repo_invotechatManager.AddUserChat(user.id, oylama.id);
                }
            }
            else
            {
                return View(oylama);//Oylama yok sayfasına yönlerdircen 
            }
            return View(oylama);
        }
        [HttpGet]
        [LoginFilter]
        [BireyselUserFilter]
        [LoglamaFilter]   
        public ActionResult OylamaBaslat()
        {
            return View();
        }


        [LoginFilter]
        [BireyselUserFilter]
        [LoglamaFilter]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult OylamaBaslat(string oylama_suresi, bool paylasima_acikmi, bool kimlik_durumu, string oylama_tipi, string urun_1, string urun_2, string urun_3, string urun_aciklamasi_1_1, string urun_aciklamasi_1_2, string urun_aciklamasi_1_3, string urun_aciklamasi_2_1, string urun_aciklamasi_2_2, string urun_aciklamasi_2_3, string urun_aciklamasi_3_1, string urun_aciklamasi_3_2, string urun_aciklamasi_3_3)
        {
            VotedressUser user = new VotedressUser();
            user = Session["login"] as VotedressUser;

            OylamaManager oylama_manager = new OylamaManager();

            bool sonuc = oylama_manager.OylamaEkle(user.id, oylama_suresi, oylama_tipi, paylasima_acikmi, kimlik_durumu, Request.Files ,urun_1, urun_2, urun_3, urun_aciklamasi_1_1, urun_aciklamasi_1_2, urun_aciklamasi_1_3, urun_aciklamasi_2_1, urun_aciklamasi_2_2, urun_aciklamasi_2_3, urun_aciklamasi_3_1, urun_aciklamasi_3_2, urun_aciklamasi_3_3);


            if (sonuc == true)
            {
                return RedirectToAction("Oylamalarim","Profile");
            }

            return RedirectToAction("OylamaBaslatilamadi");

        }

        [LoginFilter]
        [BireyselUserFilter]
        [HttpPost]
        public JsonResult Oyla(int id)
        {
            VotedressUser user = new VotedressUser();
            user = Session["login"] as VotedressUser;

            OylamaManager oylama_manager = new OylamaManager();

            bool sonuc = oylama_manager.Oyla(user, id);

            if (sonuc == true)
            {
                Vote_sade yeni_oylama = oylama_manager.OylamaGetirOylamakIcin(user.id);

                return Json(new { YeniOylama = yeni_oylama, IsSuccess = true, Message = "Oylama Başarılı" }, JsonRequestBehavior.AllowGet);

            }


            return Json(new { IsSuccess = false, Message = "Oylama Başarısız" }, JsonRequestBehavior.AllowGet);
        }

        [LoginFilter]
        [BireyselUserFilter]
        [HttpPost]
        public JsonResult OylamamiGetir(Guid oylamaId)
        {
            VotedressUser user = new VotedressUser();
            user = Session["login"] as VotedressUser;


            OylamaManager oylamaManager = new OylamaManager();
            Vote_sade vote_Sade= oylamaManager.OylamaGetir(oylamaId,user.id);


            return Json(vote_Sade, JsonRequestBehavior.AllowGet);
        }


    }
}

Votedress.WebApp/Views/Navbar/KısaYollar.cshtml
@model Votedress.Entities.ViewModellerim.KısaYollarViewModel
@using Votedress.Entities.VeritabaniModellerim
@{
    VotedressUser kullanici = Session["login"] as VotedressUser;
}
<script type="text/javascript">
    var model = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(this.Model.Bahsedenler));
    var modelArkadaslikIstekleri =@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(this.Model.ArkadaslikIsteklerim));
    var modelSepetim =@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(this.Model.Cart_Sades));
    var kullaniciResmi=@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(kullanici.ProfileImage));
    app.value("viewModel2", model);
</script>
<li class="dropdown dropdown-extended dropdown-inbox" id="arkadaslik_istekleri2" tabindex="" ng-controller="ArkadaslikIstekleriCtrl">
    <a href="javascript:;" class="dropdown-toggle" id="arkadaslik_istekleri">
        <i class="fa fa-user-plus"></i>
        <span class="badge badge-default"> {{arkadaslikIstekleri.length}} </span>
    </a>
    <ul class="dropdown-menu">
        <li class="external">
            <h3>
                <span class="bold">Arkadaşlık İstekleri</span> <br />
            </h3>

        </li>
        <li>
            <ul class="dropdown-menu-list scroller" style="height: 324px;background-color:white;overflow-y:scroll">
                <li class="arkadaslik_istegi" ng-repeat="arkadaslikIstegi in arkadaslikIstekleri"> 
                    <span class="photo">
                        <img ng-src="{{arkadaslikIstegi.UserProfileImage}}" class="img-circle" alt="">
                    </span>
                    <span class="subject">
                        <span class="from">{{arkadaslikIstegi.UserNameSurname}}</span>
                    </span>
                    <button class="btn-success" ng-click="ArkadaslikIstegiKabulEt(arkadaslikIstegi)">Kabul Et</button>
                    <button class="btn-success" ng-click="ArkadaslikIstegiSil(arkadaslikIstegi)">İsteği Sil</button>
                </li>
            </ul>
        </li>
    </ul>
</li>

<li class="dropdown dropdown-extended dropdown-inbox" id="bahsedildiginiz_oylamalar2" ng-controller="BahsedenlerCtrl">
    <a id="bahsedildiginiz_oylamalar" href="javascript:;" class="dropdown-toggle">
        <i class="icon-bell"></i>
        <span class="badge badge-default"> {{BahsedilgimYerler.length}} </span>
    </a>
    <ul class="dropdown-menu">
        <li class="external">
            <h3>
                <span class="bold">Bahsedildiğiniz Yerler</span> <br />
            </h3>

        </li>
        <li>
            <ul class="dropdown-menu-list " style="height: 275px;overflow-y:scroll;background-color:white;">
                <li ng-repeat="x in BahsedilgimYerler">
                    <a href="#" ng-click="OylamayaGit(x.OylamaId)">
                        <span class="photo">
                            <img ng-src="{{x.Bahseden.ProfileImage}}" class="img-circle" alt="">
                        </span>
                        <span class="subject">
                            <span class="from">{{x.Bahseden.Name}} {{x.Bahseden.SurName}},</span>
                            <span class="from">{{x.bahsedilenYerAdi}}'da Sizden Bahsetti </span>


                        </span>
                        <span class="message" ng-bind-html="x.Mesaj | trustAsHtmlBahsedilme"></span>

                        <span style="margin-left:45px">{{x.BahsetmeTarihi | mydate | date:'medium'}} </span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</li>
<!-- END NOTIFICATION DROPDOWN -->
<!-- BEGIN INBOX DROPDOWN -->
<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
<li class="dropdown dropdown-extended dropdown-inbox" id="mesajlar2">
    <a id="mesajlar" href="javascript:;" class="dropdown-toggle">
        <i class="icon-envelope-open"></i>
        <span class="badge badge-default" id="gorulmemis_mesajlar1">@Model.GorulmemisMesajlar.Count</span>
    </a>
    <ul class="dropdown-menu">
        <li class="external">
            <h3>
                <span class="bold" id="gorulmemis_mesajlar2">@Model.GorulmemisMesajlar.Count </span> Yeni mesajınız var
            </h3>
        </li>
        <li>
            <ul id="gorulmemis_mesajlar" class="dropdown-menu-list scroller" style="height: 275px;background-color:white;">
                @for (int i = 0; i < Model.GorulmemisMesajlar.Count; i++)
                {
                    <li id="gorulmemis_mesaj_@Model.GorulmemisMesajlar[i].userId" data-id="@Model.GorulmemisMesajlar[i].userId">
                        <a href="#">
                            <span class="photo">
                                <img src="@Model.GorulmemisMesajlar[i].ProfilImage" class="img-circle" alt="">
                            </span>
                            <span class="subject">
                                <span class="from"> @Model.GorulmemisMesajlar[i].adSoyad</span>

                            </span>
                            <span class="time" style="font-size:11px">@Model.GorulmemisMesajlar[i].GonderilmeTarihi</span>
                            @if (Model.GorulmemisMesajlar[i].Message.Length > 30)
                            {
                                <span class="message" style="font-size:15px">@Model.GorulmemisMesajlar[i].Message.Substring(0, 30)  </span>
                            }
                            else
                            {
                                <span class="message" style="font-size:15px">@Model.GorulmemisMesajlar[i].Message  </span>
                            }

                        </a>
                    </li>
                }
            </ul>
        </li>
    </ul>
</li>
<!-- END INBOX DROPDOWN -->
<!-- BEGIN TODO DROPDOWN -->
<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
<li class="dropdown dropdown-extended dropdown-tasks" id="takip_edilenler2">
    <a id="takip_edilenler" href="javascript:;" class="dropdown-toggle">
        <i class="fa fa-tags"></i>
        <span class="badge badge-default"> 0 </span>
    </a>
    <ul class="dropdown-menu extended tasks">
        <li class="external">
            <h3>
                <span class="bold">Takip Ettiğiniz Oylamalar</span>
            </h3>
            <a href="app_todo.html"></a>
        </li>
        <li>
            <ul class="dropdown-menu-list scroller" style="height: 275px;background-color:white;">
     
            </ul>
        </li>
    </ul>
</li>
<!-- END TODO DROPDOWN -->
<li class="dropdown dropdown-extended dropdown-inbox" id="sepet2" tabindex="">
    <a href="javascript:;" class="dropdown-toggle" id="sepet">
        <i class="fa fa-shopping-cart"></i>
        <span class="badge badge-default"> {{Sepetim.length}} </span>
    </a>
    <ul class="dropdown-menu">
        <li class="external">
            <h3>
                <span class="bold">Sepetim</span> <br />
            </h3>

        </li>
        <li>
            <ul class="dropdown-menu-list" style="height: 310px;background-color:white;overflow-y:scroll">
                <li class="arkadaslik_istegi" style="padding-bottom:12px" ng-repeat="sepet in Sepetim">
                    <span class="photo">
                        <img ng-src="{{sepet.ProductImage}}" class="img-circle" style="margin-top:-10px">
                    </span>
                    <span class="subject" style="margin-top:-8px">
                        <span class="from" style="margin-top:-10px"> {{sepet.ProductName}} </span>
                        <i class="fa fa-close" style="float:right;margin-top:5px;font-size:20px" ng-click="SepettenSil(sepet.id)"></i>
                        <span style="float:right;margin-right:25px;margin-top:3px">x{{sepet.Count}}</span>
                    </span>
                    <span class="subject">
                        <span> {{sepet.ProductPrice}} ₺ </span>
                    </span>
                </li>
            </ul>
            <div class="row">
                <span style="float:right;margin-right:95px">Toplam:{{ToplamTutar}} ₺</span>
            </div>

            <div class="row" style="margin-bottom:10px">
                <a href="@Url.Action("OdemeYeri","Gardrop")" class="btn  btn-success btn-sm" style="float:right;margin-right:80px">Alışverişi tamamla</a>
            </div>
        </li>
    </ul>
</li>
<!-- BEGIN USER LOGIN DROPDOWN -->
<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->

<li class="dropdown dropdown-user" style="margin-left:-11px">
    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <img alt="" class="img-circle" src="@kullanici.ProfileImage" />

        <span class="username username-hide-on-mobile"> @kullanici.UserDetail.Name </span>
        <i class="fa fa-angle-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-menu-default">
        <li>
            <a href="@Url.Action("Index","Profile")">
                <i class="icon-user"></i> Profil
            </a>
        </li>
        <li>
            <a href="@Url.Action("OylamaBaslat","Oylama")">
                <i class="fa fa-hourglass-start"></i> Oylama Başlat
            </a>
        </li>
        <li>
            <a href="@Url.Action("Oylamalarim","Profile")">
                <i class="fa fa-balance-scale"></i> Oylamalarım
                <span class="badge badge-danger"> 3 </span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index","Profile",new { sekme="siparisler"})">
                <i class="fa fa-truck"></i> Siparişlerim
                <span class="badge badge-success"> 1 </span>
            </a>
        </li>
        <li class="divider"> </li>
        <li id="Cikis">
            <a>
                <i class="icon-key"></i>Çıkış
            </a>
        </li>
    </ul>
</li>